"""init: 8개 테이블 생성

Revision ID: 8aee7b427057
Revises: 
Create Date: 2026-04-13 21:34:45.396154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aee7b427057'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_req_res_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('callId', sa.String(length=36), nullable=False),
    sa.Column('itemId', sa.Integer(), nullable=True),
    sa.Column('apiType', sa.String(length=20), nullable=False),
    sa.Column('event', sa.String(length=10), nullable=False),
    sa.Column('requestBody', sa.JSON(), nullable=True),
    sa.Column('responseBody', sa.JSON(), nullable=True),
    sa.Column('httpStatus', sa.Integer(), nullable=True),
    sa.Column('durationMs', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('callId')
    )
    op.create_table('item_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('itemId', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('cleanedTitle', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('analyzedPrice', sa.Integer(), nullable=True),
    sa.Column('vector', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('sellerId', sa.String(length=50), nullable=False),
    sa.Column('sellerReliability', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('askingPrice', sa.Integer(), nullable=False),
    sa.Column('estimatedPrice', sa.Integer(), nullable=True),
    sa.Column('priceDiffPercent', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('llmConfidence', sa.Integer(), nullable=True),
    sa.Column('llmReason', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failStage', sa.String(length=30), nullable=True),
    sa.Column('failReason', sa.String(length=50), nullable=True),
    sa.Column('collectedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analyzedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notifiedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('itemId')
    )
    op.create_table('pipeline_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.Column('sellerId', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('event', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('avgPrice', sa.Integer(), nullable=False),
    sa.Column('minPrice', sa.Integer(), nullable=True),
    sa.Column('maxPrice', sa.Integer(), nullable=True),
    sa.Column('sampleCount', sa.Integer(), nullable=False),
    sa.Column('snapshotDate', sa.Date(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watch_keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('maxPrice', sa.Integer(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.Column('imageUrl', sa.String(length=500), nullable=False),
    sa.Column('imageOrder', sa.Integer(), nullable=False),
    sa.Column('analysisResult', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['itemId'], ['items.itemId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.Column('notifyType', sa.String(length=20), nullable=False),
    sa.Column('notifyStatus', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('processedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resultDetail', sa.JSON(), nullable=True),
    sa.Column('errorDetail', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['itemId'], ['items.itemId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_logs')
    op.drop_table('item_images')
    op.drop_table('watch_keywords')
    op.drop_table('price_history')
    op.drop_table('pipeline_logs')
    op.drop_table('items')
    op.drop_table('item_embeddings')
    op.drop_table('api_req_res_logs')
    # ### end Alembic commands ###
